version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base

    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - '2000'
    ports:
      - '7000:2000'
    command: npm run dev

  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=postgres
      - APP_DB_PASS=12345
      - APP_DB_NAME=tomodb
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data
      # - ./db:/docker-entrypoint-initdb.d/
      - ./db/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - 5433:5432