version: '3'

services:
  backend:
    working_dir: /home/node/app
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: base
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - /home/aot/my_projects/tomo-app/src:/home/node/app/src
    container_name: ts-node-docker
    expose:
      - '3000'
    ports:
      - '${BACKEND_PORT}:3000'
    command: yarn dev

  postgres:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
      target: base
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASS=${APP_DB_PASS}
      - APP_DB_NAME=${APP_DB_NAME}
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data
      - ./db/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - 5433:5432